import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

final color= <Color>[
  Colors.yellow,
  Colors.black,
  Colors.blue,
  Colors.red,
  Colors.pink,
  Colors.orange,
  Colors.purple,
  Colors.cyan,
  Colors.grey,
  Colors.lime,
  Colors.deepPurple,
  Colors.tealAccent,
  Colors.amber,
  Colors.red,
  Colors.pink,
  Colors.orange,
  Colors.purple,
  Colors.cyan,
  Colors.grey,
  Colors.yellow,
  Colors.black,
  Colors.blue,
  Colors.red,
  Colors.pink,
  Colors.orange,
  Colors.purple,
  Colors.cyan,
];